# Generated by Django 5.1.4 on 2024-12-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_sharing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ops', 'Operation User'), ('client', 'Client User')], default='ops', max_length=10),
        ),
    ]
